name: fliclib
description: A library to use Flic 2 bluetooth Smart Button with dart and flutter. Built to use the Flic 2 TCP Protocol Specification.
version: 1.0.0-dev.2
homepage: https://github.com/indiealexh/dart-fliclib

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
